[package]
name = "brooksmtownsend-smartrelease-demo-mylibb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brooksmtownsend-smartrelease-demo-mylibc = { version = "0.1.0", path = "../mylibc" }
